# --- Configuración del Servidor ---
server.port=${SERVER_PORT}

# Ruta de la carpeta de datasets
# vincular con cludinary!!
# dataset.folder = fuente-estatica/src/main/resources/datasets

# --- Configuración de la Base de Datos (JDBC) ---
spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}

# IMPORTANTE: Spring Boot usa la propiedad 'spring.datasource.driver-class-name'.
# La variable de entorno que estás usando es 'SPRING_DATASOURCE_DRIVER-CLASS-NAME', que
# Spring Boot puede mapear automáticamente, pero para consistencia, es mejor mapearla
# a la propiedad estándar si se pasa como variable de entorno.
spring.datasource.driver-class-name=${SPRING_DATASOURCE_DRIVER_CLASS_NAME}

# --- Configuración del ORM (Hibernate) ---
spring.jpa.hibernate.ddl-auto=${SPRING_JPA_HIBERNATE_DDL_AUTO}
spring.jpa.show-sql=${SPRING_JPA_SHOW_SQL}
spring.jpa.properties.hibernate.format_sql=${SPRING_JPA_PROPERTIES_HIBERNATE_FORMAT_SQL}
spring.jpa.properties.hibernate.dialect=${SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT}

# --- Configuración de Carga de Archivos (Multipart) ---
spring.servlet.multipart.enabled=${SPRING_SERVLET_MULTIPART_ENABLED}
