@startuml

class Hecho{
- título: String
- descripción: String
- categoría: Categoria
- contenidoMultimedia : ???
- lugarAcontecimiento: Coordenada
- fechaDeCarga : LocalDateTime
- fechaAcontecimiento: LocalDate
- origen: Fuente
- solicitudesEliminacion: HashSet<SolicitudDeEliminacion>
- eliminado: boolean

+ print(): void
+ aniadirSolicitud(SolicitudDeEliminacion solicitud): void
}

class Categoria{
- nombre: String
--
+ Categoria(String nombre): void
}

class Contribuyente{
- nombre: String
- apellido: String
- edad: Integer
--
+ solicitarEliminacionDeHecho(Hecho hecho, String descripcion): void
}

class Administrador {
--
+ crearColeccion(String titulo, String descripcion, Fuente fuente): Coleccion
+ importarHechosCSV()
+ juzgarEliminacionDeHecho(Hecho): void
}

class Coleccion{
- titulo: String
- descripcion: String
- hechos: HashSet<Hecho>
- fuente: Fuente
- criterioDePertenencia: Criterio


+ getHechos(): HashSet<Hecho>
+ agregarHecho(Hecho hecho)): void
+ navegarHechosFiltrados(??????): HashSet<Hecho>
+ eliminarHecho(Hecho hecho): void
}

class SolicitudDeEliminacion{
- descripcion: String
- hecho: Hecho
- estado : boolean
--
+ aceptar(): void
+ rechazar(): void
}

class Fuente{
- hechos: List<Hecho>

}

class FuenteEstatica{

+ consultarCSV(String archivo): List<Hecho>
+ setearFechaHecho(String fechaString,Hecho h): void
}

class Coordenada{
- latitud : float
- longitud : float
--
+ Coordenada(float latitud, float longitud): Coordenada
+ comoArray() : float[]
}

Contribuyente .d.> Fuente
Administrador .d.> Fuente

Hecho --> Coordenada
Hecho -r->"*" Categoria
Hecho -d->"*" SolicitudDeEliminacion
Coleccion -->"*" Hecho

Hecho --> Fuente
Coleccion -r-> Fuente

Fuente -->"*" Hecho

FuenteEstatica -u-|> Fuente
FuenteDinamica -u-|> Fuente
FuenteProxy -u-|> Fuente



@enduml