@startuml

class Hecho{
+ enum Origen
+ enum Campos
- título: String
- descripción: String
- categoría: Categoria
- origen: Origen
- lugarAcontecimiento: Coordenada
- fechaHecho: LocalDate
- fechaDeCarga: LocalDateTime
- eliminado: boolean
- solicitudesDeEliminacion: List<SolicitudDeEliminacion>
- etiquetas: HashSet<String>
--
+ solicitarEliminacion(String justificacion): SolicitudDeEliminacion
+ etiquetar(String etiqueta): void
}

class Categoria{
- nombre: String
}


class Coleccion{
- titulo: String
- descripcion: String
- fuente: Fuente
- criterioDePertenencia: Criterio
- hechos: List<Hecho>
--
+ contiene (Hecho hecho): boolean
+ recalcularHechos(): void
}

class Criterio{
- filtros: ArrayList<Predicate<Hecho>>
--
+ aplicarA(List<Hecho> listaOriginal): List<Hecho>
}


class SolicitudDeEliminacion{
+ enum Estado
- descripcion: String
- hecho: Hecho
- fechaDeCarga: LocalDateTime
- fechaDeResolucion: LocalDateTime
- estado: Estado
--
+ aceptar(): void
+ rechazar(): void
+ estaPendiente(): boolean
}

interface Fuente{
+ getHechos(): ArrayList<Hecho>
}

class FuenteEstatica{
- archivo: String
--
+ getHechos(): ArrayList<Hecho>
}

class Coordenada{
- latitud : double
- longitud : double
--
+ comoArray() : double[]
+ equals(Coordenada other): boolean
}



Hecho --> Categoria
Hecho --> Coordenada
Hecho -->"*" SolicitudDeEliminacion

Coleccion -r-> Fuente
Coleccion --> Criterio
Coleccion -->"*" Hecho

Criterio .r.> Hecho

SolicitudDeEliminacion --> Hecho

FuenteEstatica .u.|> Fuente
FuenteEstatica .l.> Hecho


@enduml