@startuml

class Hecho{
private Long id;
    - titulo: String
    - descripcion: String
    - categoria: Categoria
    - contenidoMultimedia: ContenidoMultimedia
    - lugarAcontecimiento: Coordenada
    - fechaHecho: LocalDate
    - fechaDeCarga: LocalDateTime
    - eliminado: boolean
    - Contribuyente contribuyente;
    - lastUpdate: LocalDateTime
    - solicitudDeModificacion : SolicitudDeModificacion
    - etiquetas: HashSet<Etiqueta>
}

enum OrigenHecho{
CARGA_MANUAL
CONTRIBUYENTE
DATASET
PROXY
}

class Categoria{
- nombre: String
}

class Etiqueta{
- nombre: String
}

class ContenidoMultimedia{
}

enum EstadoSolicitud {
    PENDIENTE
    ACEPTADA
    SUGERIDOACAMBIO
    RECHAZADA
    ACEPTADACONSUGERENCIA
    RECHAZADOPORSPAM
}


class Coordenada{
- latitud: Double
- longitud: Double
--
+ comoArray(): Double[]
+ equals(other: Coordenada): boolean
}

class Administrador{
- nombre: String
- apellido: String
}

class Contribuyente{
- id: Long
- nombre: String
- apellido: String
- fechaNacimiento: LocalDate
--
+ getEdad(): int
}

class SolicitudDeModificacion {
- hechoViejo: Hecho;
- hechoNuevo: Hecho;
- estado: EstadoSolicitud;
- motivoDeEstado: String;
--
+ resolver(ResolucionDTO resolucion): void
}

Hecho --> Categoria
Hecho --> ContenidoMultimedia
Hecho --> OrigenHecho
Hecho --> Coordenada
Hecho --> Contribuyente
Hecho --> SolicitudDeModificacion
Hecho -->"*" Etiqueta

SolicitudDeModificacion --> Hecho
SolicitudDeModificacion --> EstadoSolicitud
SolicitudDeModificacion --> Administrador

@enduml