package ar.utn.ba.ddsi.models.entities;

public enum TipoEstadistica {
  PROVINCIA_CON_MAS_HECHOS_POR_COLECCION,
  CATEGORIA_CON_MAS_HECHOS,
  PROVINCIA_CON_MAS_HECHOS_POR_CATEGORIA,
  HORA_CON_MAS_HECHOS_POR_CATEGORIA,
  SOLICITUDES_DE_ELIMINACION_SPAM
}
