# --- 1. Configuración del Servidor ---
server.port=${SERVER_PORT}

# Ruta de imágenes local (es mejor quitar esta línea o comentarla si vas a usar Cloudinary)
# imagenes.folder = C:/Users/Juan M/Desktop/UTN/3er año/Diseño de sistemas/Imagenes


# --- 2. Configuración de la Base de Datos (JDBC) ---
spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}
spring.datasource.driver-class-name=${SPRING_DATASOURCE_DRIVER_CLASS_NAME}

# --- 3. Configuración del ORM (Hibernate) ---
# Sincronización de entities contra la base de datos
spring.jpa.hibernate.ddl-auto=${SPRING_JPA_HIBERNATE_DDL_AUTO}
spring.jpa.show-sql=${SPRING_JPA_SHOW_SQL}
spring.jpa.properties.hibernate.format_sql=${SPRING_JPA_PROPERTIES_HIBERNATE_FORMAT_SQL}
spring.jpa.properties.hibernate.dialect=${SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT}


# --- 4. Variables de Configuración Específicas del Servicio Dinámica ---

# Configuración del secreto para JWT (o uso general)
secret.string=${SECRET_STRING}

# Configuración del servicio Cloudinary para almacenamiento de imágenes
cloudinary.cloud.name=${CLOUDINARY_CLOUD_NAME}
cloudinary.api.key=${CLOUDINARY_API_KEY}
cloudinary.api.secret=${CLOUDINARY_API_SECRET}
