# --- 1. Configuración del Servidor ---
server.port=${SERVER_PORT}

# --- 2. Configuración de Conexión a OTROS Servicios (URLs de Despliegue) ---
# Usamos las URLs del dominio .dds.apps.disilab.ar
fuente.estatica.api.base-url=${FUENTE_ESTATICA_API_BASE_URL}
fuente.dinamica.api.base-url=${FUENTE_DINAMICA_API_BASE_URL}
fuente.proxy.api.base-url=${FUENTE_PROXY_API_BASE_URL}
auth.service.url=${AUTH_SERVICE_URL}
georef.api.base-url=${GEOREF_API_BASE_URL} # Esta URL es externa, se mantiene como variable

# --- 3. Configuración de la Base de Datos (JDBC) ---
spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}
spring.datasource.driver-class-name=${SPRING_DATASOURCE_DRIVER_CLASS_NAME}

# --- 4. Configuración del ORM (Hibernate) ---
spring.jpa.hibernate.ddl-auto=${SPRING_JPA_HIBERNATE_DDL_AUTO}
spring.jpa.show-sql=${SPRING_JPA_SHOW_SQL}
spring.jpa.properties.hibernate.format_sql=${SPRING_JPA_PROPERTIES_HIBERNATE_FORMAT_SQL}
spring.jpa.properties.hibernate.dialect=${SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT}


# --- 5. Variables de Configuración Específicas del Servicio (Seguridad/Tokens) ---

# Configuración del secreto para JWT
secret.string=${SECRET_STRING}

# Configuración de credenciales de cliente (OAuth2 o similar)
service.client.id=${SERVICE_CLIENT_ID}
service.client.secret=${SERVICE_CLIENT_SECRET}
