server.port=8080
fuente.estatica.api.base-url=http://localhost:8081
fuente.dinamica.api.base-url=http://localhost:8082
fuente.proxy.api.base-url=http://localhost:8083
auth.service.url=http://localhost:8086
georef.api.base-url=https://apis.datos.gob.ar/georef/api

spring.datasource.url=jdbc:mysql://localhost:3306/tpa_agregador?useSSL=false&serverTimezone=UTC&createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Configuraci?n del ORM cada vez que levantemos el servidor (sincronización de entities contra la base de datos)
spring.jpa.hibernate.ddl-auto=update
# none: no toca la BD.
# validate: valida que las entidades coincidan con la BD.
# update: actualiza la BD seg?n las entidades. Si hacemos un cambio en el nombre de alguna columna por ejemplo => Cuando volvamos a levantar el servidor
# el ORM lo actualizara automaticamente
# create: crea las tablas en cada inicio pero no las actualiza
# create-drop: igual que create pero borra al apagar.

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect