# --- 1. Configuración del Servidor ---
server.port=${SERVER_PORT}

# --- 2. Configuración de Conexión a OTROS Microservicios (Endpoints de Despliegue) ---
# El Frontend necesita las URLs para consumir los datos y la autenticación

# 🚨 Gateway/Agregador (Ruta principal de datos)
servicio.agregador.api.base-url=${SERVICIO_AGREGADOR_API_BASE_URL}

# 🚨 Servicio de Usuarios (Para registro, perfiles, etc.)
servicio.usuarios.api.base-url=${SERVICIO_USUARIOS_API_BASE_URL}

# 🚨 Autenticación (Endpoint de login/tokens, típicamente dentro del Servicio de Usuarios)
auth.service.url=${AUTH_SERVICE_URL}
spring.servlet.multipart.max.file.size=${SPRING_SERVLET_MULTIPART_MAX_FILE_SIZE}


# 🚨 Servicios de Fuente (Acceso directo a datos específicos si es necesario)
fuente.dinamica.api.base-url=${FUENTE_DINAMICA_API_BASE_URL}
fuente.estatica.api.base-url=${FUENTE_ESTATICA_API_BASE_URL}
server.forward-headers-strategy=native
