@startuml

class Administrador{
- nombre: String
- apellido: String
}

enum CamposHecho{
    TITULO
    DESCRIPCION
    CATEGORIA
    LATITUD
    LONGITUD
    FECHADEHECHO
}


class Categoria{
- nombre: String
}

class ContenidoMultimedia{
}


enum EstadoSolicitud {
    PENDIENTE
    ACEPTADA
    SUGERIDOACAMBIO
    RECHAZADA
    ACEPTADACONSUGERENCIA
}

class Etiqueta{
- nombre: String
}

class Coordenada{
- latitud: Double
- longitud: Double
--
+ comoArray(): Double[]
+ equals(other: Coordenada): boolean
}

class Hecho{
- título: String
- descripción: String
- categoría: Categoria
- lugarAcontecimiento: Coordenada
- fechaHecho: LocalDate
- fechaDeCarga: LocalDateTime
- id: Long
- idDataset: Long
}

class LectorDeCSV{
- pathArchivo: PathDataset
--
- leerHechosDeCSV(): ArrayList<Hecho>
- getHechos(): ArrayList<Hecho>
}

enum OrigenHecho{
CARGA_MANUAL
CONTRIBUYENTE
DATASET
PROXY
}


class Contribuyente{
- id: Long
- nombre: String
- apellido: String
- fechaNacimiento: LocalDate
--
+ getEdad(): int
}

class PathDataset{
- id: Long
- path: String
- fechaCarga: LocalDateTime
}

class SolicitudDeEliminacion{
- descripción: String
- hecho: Hecho
- fechaCarga: LocalDateTime
- fechaDeResolucion: LocalDateTime
- estado: EstadoSolicitud
- solicitante: Contribuyente
- administradorQueResolvio: Administrador
- CANT_MINIMA_DE_CARACTERES: int = 500
}

Hecho --> Categoria
Hecho --> ContenidoMultimedia
Hecho --> OrigenHecho
Hecho --> Coordenada
Hecho -->"*" SolicitudDeEliminacion
Hecho -->"*" Etiqueta
Hecho ..> Contribuyente

LectorDeCSV *--> Hecho
LectorDeCSV ..> CamposHecho
LectorDeCSV --> PathDataset

SolicitudDeEliminacion --> Hecho
SolicitudDeEliminacion --> EstadoSolicitud
SolicitudDeEliminacion --> Contribuyente
SolicitudDeEliminacion --> Administrador

@enduml