# --- 1. Configuración del Servidor ---
server.port=${SERVER_PORT}

# --- 2. Configuración de la Base de Datos (JDBC) ---
spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}
spring.datasource.driver-class-name=${SPRING_DATASOURCE_DRIVER_CLASS_NAME}

# --- 3. Configuración del ORM (Hibernate) ---

# Sincronización de entities contra la base de datos
spring.jpa.hibernate.ddl-auto=${SPRING_JPA_HIBERNATE_DDL_AUTO}
# none: no toca la BD.
# validate: valida que las entidades coincidan con la BD.
# update: actualiza la BD segun las entidades.

spring.jpa.show-sql=${SPRING_JPA_SHOW_SQL}
spring.jpa.properties.hibernate.format_sql=${SPRING_JPA_PROPERTIES_HIBERNATE_FORMAT_SQL}
spring.jpa.properties.hibernate.dialect=${SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT}


# --- 4. Variables de Configuración Específicas del Servicio (Seguridad/Tokens) ---

# Configuración del secreto para JWT
secret.string=${SECRET_STRING}

# Configuración de credenciales de cliente (OAuth2 o similar, para que otros servicios se identifiquen)
service.client.id=${SERVICE_CLIENT_ID}
service.client.secret=${SERVICE_CLIENT_SECRET}
